export const ENVIRONMENTS = {
	FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
	FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '',
	FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '',
	FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '',
	FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
	FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '',

	BASE_URL: process.env.NEXT_PUBLIC_BASE_URL || '',
	STORAGE_KEY: process.env.NEXT_PUBLIC_STORAGE_KEY || '',
	PLANNING_STORAGE_KEY: process.env.NEXT_PUBLIC_PLANNING_STORAGE_KEY || '',
}

export const DOC_HEIGHT = '--doc-height'
